name: rick_and_morty
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  injectable: ^2.5.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  gap: ^3.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  either_dart: ^1.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
